import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Mulish } from 'next/font/google';
import Header from "./components/Header";
import SidePanel from "./components/SidePanel";
import "./globals.css";
import QueryProvider from "@/app/providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const mulish = Mulish({
    variable: "--font-mulish",
    display: 'swap',
    subsets: ["latin", "cyrillic"],
    weight: ['400', '600', '900'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="uk">
            <body className={`${mulish.variable} font-sans antialiased`}>
                <QueryProvider>
                    {children}
                </QueryProvider>
            </body>
        </html>
    );
}