# Generated by Django 5.2.8 on 2026-01-18 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm', models.BooleanField(blank=True)),
                ('bar', models.BooleanField(blank=True)),
                ('byo', models.BooleanField(blank=True)),
                ('essential_reservation', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('place_id', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('region', models.TextField()),
                ('country', models.TextField()),
                ('popularity', models.FloatField()),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.TextField()),
                ('website', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.category')),
                ('pictures', models.ManyToManyField(to='places.pictures')),
            ],
        ),
    ]
