# Generated by Django 5.1.5 on 2026-03-08 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('profiles', '0002_delete_favouriteplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_places', to='profiles.userprofile')),
            ],
        ),
    ]
