# Generated by Django 5.1.5 on 2026-03-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouritePlace',
        ),
    ]
